In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\sanja\Documents\NBA STATS PROJECT - PYTHON\sportsref_download.xlsx", header = 1)
df

,Rk,Season,Lg,Age,Ht,Wt,G,MP,FG,FGA,...,FG%,3P%,FT%,Pace,eFG%,TOV%,ORB%,FT/FGA,ORtg,TS%
0,1,2025-26,NBA,26.1,2026-06-07,216.0,1011,241.4,41.8,89.1,...,0.469,0.358,0.783,99.3,0.543,12.8,26.0,0.207,115.4,0.580
1,2,2024-25,NBA,26.3,2026-06-07,216.0,1230,241.3,41.7,89.2,...,0.467,0.360,0.780,98.8,0.543,12.6,25.2,0.189,114.5,0.576
2,3,2023-24,NBA,26.4,2026-06-06,217.0,1230,241.4,42.2,88.9,...,0.474,0.366,0.784,98.5,0.547,12.1,24.2,0.192,115.3,0.580
3,4,2022-23,NBA,26.1,2026-06-06,217.0,1230,241.8,42.0,88.3,...,0.475,0.361,0.782,99.2,0.545,12.5,24.0,0.208,114.8,0.581
4,5,2021-22,NBA,26.1,2026-06-06,216.0,1230,241.4,40.6,88.1,...,0.461,0.354,0.775,98.2,0.532,12.3,23.2,0.192,112.0,0.566
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,76,1950-51,NBA,NaN,NaT,NaN,354,NaN,29.8,83.6,...,0.357,NaN,0.733,NaN,0.357,NaN,NaN,0.293,NaN,0.428
76,77,1949-50,NBA,NaN,NaT,NaN,561,NaN,28.2,83.1,...,0.340,NaN,0.712,NaN,0.340,NaN,NaN,0.284,NaN,0.410
77,78,1948-49,BAA,NaN,NaT,NaN,360,NaN,29.0,88.7,...,0.327,NaN,0.703,NaN,0.327,NaN,NaN,0.248,NaN,0.390
78,79,1947-48,BAA,NaN,NaT,NaN,192,NaN,27.2,96.0,...,0.284,NaN,0.675,NaN,0.284,NaN,NaN,0.190,NaN,0.337
79,80,1946-47,BAA,NaN,NaT,NaN,331,NaN,25.9,92.9,...,0.279,NaN,0.641,NaN,0.279,NaN,NaN,0.171,NaN,0.326

In [3]:
df.head(23)

,Rk,Season,Lg,Age,Ht,Wt,G,MP,FG,FGA,...,FG%,3P%,FT%,Pace,eFG%,TOV%,ORB%,FT/FGA,ORtg,TS%
0,1,2025-26,NBA,26.1,2026-06-07,216.0,1011,241.4,41.8,89.1,...,0.469,0.358,0.783,99.3,0.543,12.8,26.0,0.207,115.4,0.580
1,2,2024-25,NBA,26.3,2026-06-07,216.0,1230,241.3,41.7,89.2,...,0.467,0.360,0.780,98.8,0.543,12.6,25.2,0.189,114.5,0.576
2,3,2023-24,NBA,26.4,2026-06-06,217.0,1230,241.4,42.2,88.9,...,0.474,0.366,0.784,98.5,0.547,12.1,24.2,0.192,115.3,0.580
3,4,2022-23,NBA,26.1,2026-06-06,217.0,1230,241.8,42.0,88.3,...,0.475,0.361,0.782,99.2,0.545,12.5,24.0,0.208,114.8,0.581
4,5,2021-22,NBA,26.1,2026-06-06,216.0,1230,241.4,40.6,88.1,...,0.461,0.354,0.775,98.2,0.532,12.3,23.2,0.192,112.0,0.566
5,6,2020-21,NBA,26.1,2026-06-06,218.0,1080,241.4,41.2,88.4,...,0.466,0.367,0.778,99.2,0.538,12.4,22.2,0.192,112.3,0.572
6,7,2019-20,NBA,26.1,2026-06-06,218.0,1059,241.8,40.9,88.8,...,0.460,0.358,0.773,100.3,0.529,12.8,22.5,0.201,110.6,0.565
7,8,2018-19,NBA,26.3,2026-06-06,220.0,1230,241.6,41.1,89.2,...,0.461,0.355,0.766,100.0,0.524,12.4,22.9,0.198,110.4,0.560
8,9,2017-18,NBA,26.4,2026-06-07,221.0,1230,241.4,39.6,86.1,...,0.460,0.362,0.767,97.3,0.521,13.0,22.3,0.193,108.6,0.556
9,10,2016-17,NBA,26.6,2026-06-07,222.0,1230,241.6,39.0,85.4,...,0.457,0.358,0.772,96.4,0.514,12.7,23.3,0.209,108.8,0.552
10,11,2015-16,NBA,26.7,2026-06-07,222.0,1230,241.8,38.2,84.6,...,0.452,0.354,0.757,95.8,0.502,13.2,23.8,0.209,106.4,0.541
11,12,2014-15,NBA,26.7,2026-06-07,223.0,1230,242.0,37.5,83.6,...,0.449,0.350,0.750,93.9,0.496,13.3,25.1,0.205,105.6,0.534
12,13,2013-14,NBA,26.5,2026-06-07,223.0,1230,242.0,37.7,83.0,...,0.454,0.360,0.756,93.9,0.501,13.6,25.5,0.215,106.6,0.541
13,14,2012-13,NBA,26.7,2026-06-07,223.0,1229,241.9,37.1,82.0,...,0.453,0.359,0.753,92.0,0.496,13.7,26.5,0.204,105.8,0.535
14,15,2011-12-01 00:00:00,NBA,26.6,2026-06-07,223.0,990,241.9,36.5,81.4,...,0.448,0.349,0.752,91.3,0.487,13.8,27.0,0.208,104.6,0.527
15,16,2010-11-01 00:00:00,NBA,26.6,2026-06-07,223.0,1230,241.9,37.2,81.2,...,0.459,0.358,0.763,92.1,0.498,13.4,26.4,0.229,107.3,0.541
16,17,2009-10-01 00:00:00,NBA,26.6,2026-06-07,222.0,1230,241.7,37.7,81.7,...,0.461,0.355,0.759,92.7,0.501,13.3,26.3,0.228,107.6,0.543
17,18,2008-09-01 00:00:00,NBA,26.6,2026-06-07,221.0,1230,241.7,37.1,80.9,...,0.459,0.367,0.771,91.7,0.500,13.3,26.7,0.236,108.3,0.544
18,19,2007-08-01 00:00:00,NBA,26.8,2026-06-07,220.0,1230,241.5,37.3,81.5,...,0.457,0.362,0.755,92.4,0.497,13.2,26.7,0.231,107.5,0.540
19,20,2006-07-01 00:00:00,NBA,26.6,2026-06-07,219.0,1230,242.2,36.5,79.7,...,0.458,0.358,0.752,91.9,0.496,14.2,27.1,0.246,106.5,0.541
20,21,2005-06-01 00:00:00,NBA,26.5,2026-06-07,220.0,1230,242.1,35.8,79.0,...,0.454,0.358,0.745,90.5,0.490,13.7,27.3,0.248,106.2,0.536
21,22,2004-05-01 00:00:00,NBA,26.9,2026-06-07,220.0,1230,241.9,35.9,80.3,...,0.447,0.356,0.756,90.9,0.482,13.6,28.7,0.245,106.1,0.529
22,23,2003-04-01 00:00:00,NBA,27.0,2026-06-07,220.0,1189,241.7,35.0,79.8,...,0.439,0.347,0.752,90.1,0.471,14.2,28.6,0.228,102.9,0.516

In [24]:
df['Season'] = df['Season'].astype(str).str[:7]
df2 = df.head(23)[['Season', 'PTS', '3P', '3PA', 'FGA', 'FT', 'FT/FGA']]
df2

     Season    PTS    3P   3PA   FGA    FT  FT/FGA
0   2025-26  115.3  13.3  37.0  89.1  18.5   0.207
1   2024-25  113.8  13.5  37.6  89.2  16.9   0.189
2   2023-24  114.2  12.8  35.1  88.9  17.0   0.192
3   2022-23  114.7  12.3  34.2  88.3  18.4   0.208
4   2021-22  110.6  12.4  35.2  88.1  16.9   0.192
5   2020-21  112.1  12.7  34.6  88.4  17.0   0.192
6   2019-20  111.8  12.2  34.1  88.8  17.9   0.201
7   2018-19  111.2  11.4  32.0  89.2  17.7   0.198
8   2017-18  106.3  10.5  29.0  86.1  16.6   0.193
9   2016-17  105.6   9.7  27.0  85.4  17.8   0.209
10  2015-16  102.7   8.5  24.1  84.6  17.7   0.209
11  2014-15  100.0   7.8  22.4  83.6  17.1   0.205
12  2013-14  101.0   7.7  21.5  83.0  17.8   0.215
13  2012-13   98.1   7.2  20.0  82.0  16.7   0.204
14  2011-12   96.3   6.4  18.4  81.4  16.9   0.208
15  2010-11   99.6   6.5  18.0  81.2  18.6   0.229
16  2009-10  100.4   6.4  18.1  81.7  18.6   0.228
17  2008-09  100.0   6.6  18.1  80.9  19.1   0.236
18  2007-08   99.9   6.6  18.1  81.5  18.8   0.231
19  2006-07   98.7   6.1  16.9  79.7  19.6   0.246
20  2005-06   97.0   5.7  16.0  79.0  19.6   0.248
21  2004-05   97.2   5.6  15.8  80.3  19.7   0.245
22  2003-04   93.4   5.2  14.9  79.8  18.2   0.228

In [14]:
pd.set_option('display.max_columns', 35)

In [21]:
stats = df2[['PTS', '3P', '3PA', 'FGA']].agg(['mean', 'median', 'var', 'std']).round(2)
stats

           PTS     3P     3PA    FGA
mean    103.23   5.88   16.67  88.91
median  106.00   5.60   15.80  88.40
var     115.19  15.61  115.26  62.42
std      10.73   3.95   10.74   7.90

In [29]:
df3 = df2.tail(20)

In [30]:
stats2 = df3[['PTS', '3P', '3PA', 'FGA']].agg(['mean', 'median', 'var', 'std']).round(2)
stats2

           PTS    3P    3PA    FGA
mean    102.83  8.37  23.42  83.65
median  100.20  7.45  20.75  82.50
var      38.86  6.86  52.43  11.83
std       6.23  2.62   7.24   3.44

In [28]:
df['Season'].min(), "to", df['Season'].max()

('1946-47', 'to', '2025-26')

In [31]:
df2['Season'].min(), "to", df2['Season'].max()

('2003-04', 'to', '2025-26')

In [32]:
df3['Season'].min(), "to", df3['Season'].max()

('2003-04', 'to', '2022-23')

In [36]:
with pd.ExcelWriter(r'C:\Users\sanja\Documents\NBA STATS PROJECT - PYTHON\NBA_Project_Cleaned_Data_2003-2023.xlsx') as writer:
    # Original cleaned data
    df3.to_excel(writer, sheet_name='Cleaned_Data', index=False)
    
    # Summary statistics
    stats_table = df3[['PTS', '3P', '3PA', 'FGA']].agg(['mean', 'median', 'var', 'std']).round(2)
    stats_table.to_excel(writer, sheet_name='Summary_Stats')

In [37]:
with pd.ExcelWriter(r'C:\Users\sanja\Documents\NBA STATS PROJECT - PYTHON\NBA_Project_Cleaned_Data_2003-2025.xlsx') as writer:
    # Original cleaned data (up to the most recent date)
    df2.to_excel(writer, sheet_name='Cleaned_Data', index=False)
    
    # Summary statistics (up to the most recent date)
    stats_table = df2[['PTS', '3P', '3PA', 'FGA']].agg(['mean', 'median', 'var', 'std']).round(2)
    stats_table.to_excel(writer, sheet_name='Summary_Stats')